version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: celeritas
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:latest
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data

  mariadb:
    image: docker.io/library/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: celeritas
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  postgres-data:
  redis-data:
  mariadb-data:
